spring:
  application:
    name: eCommerce_homework
  datasource:
    url: jdbc:mysql://localhost:3306/eCommerce_homework_final
    username: root
    password: seyfettin123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  main:
    allow-circular-references: true
server:
  port: 9190
